name: wheelRuts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.12
  - gdal=3.4.0
  - numpy
  - h5py
  - tqdm
  - imageio>=2.5.0
  - imgaug>=0.4.0
  - geopandas
  - pip
  - rasterio


